INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Akureyrar','gagolf.is','golf course',3);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Ásbyrgisvöllur','https://maps.app.goo.gl/kmcb9FSUUmF6aedP6','golf course',4);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Bíldudals','facebook.com/GolfklubburBildudals/','golf course',7);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn Ós','facebook.com/golfgos/','golf course',9);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Syðridalsvöllur','bolungarvik.is/golf/','golf course',10);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Borganess','gbgolf.is','golf course',12);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn Hamar','www.ghdgolf.net','golf course',14);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Fljótsdalshéraðs','https://www.facebook.com/golfklubbur','golf course',18);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Byggðarholts','facebook.com/gbeesk/','golf course',19);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Þorlákshafnar','facebook.com/golfklubburthorlakshafnar','golf course',20);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Ísafjarðar','golfisa.is','golf course',22);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn Flúðir','kaffisel.is','golf course',23);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Kópavogs og Garðabæjar','www.gkg.is','golf course',24);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Sandgerðis','gsggolf.is','golf course',25);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Mývatnssveitar','facebook.com/Golfkl%C3%BAbbur-M%C3%BDvatnssveitar-221129381255298/','golf course',27);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Grindavíkur','gggolf.is','golf course',28);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Geysir Golf','www.geysirgolf.is','golf course',30);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn Keilir','keilir.is','golf course',31);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Hellu','ghr.is','golf course',34);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn Jökull','facebook.com/Golfkl%C3%BAbburinn-J%C3%B6kull-%C3%93lafsv%C3%ADk-1178725165481292/','golf course',35);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Hornafjarðar','ghhgolf.is','golf course',36);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Hólmavíkur','facebook.com/groups/814630825571415','golf course',37);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfvöllurinn á Húsafelli','husafell.is/afthreying/golfvollur','golf course',38);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Hveragerðis Gufudal','www.ghg.is','golf course',40);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfvöllurinn á Hellishólum','hellisholar.is','golf course',41);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Ísafjarðar','golfisa.is','golf course',42);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Suðurnesja','www.gs.is','golf course',43);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfvöllurinn Brautarholti','gbr.is','golf course',45);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Kópavogs og Garðabæjar','www.gkg.is','golf course',47);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn Dalbúi','dalbui.is','golf course',49);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Mosfellsbæjar','golfmos.is','golf course',51);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Mývatnssveitar','facebook.com/Golfkl%C3%BAbbur-M%C3%BDvatnssveitar-221129381255298/','golf course',52);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Norðfjarðar','www.golf740.is','golf course',53);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Fjallabyggðar','facebook.com/Golfkl%C3%BAbbur-Fjallabygg%C3%B0ar-163895736996205/','golf course',54);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn Jökull','facebook.com/Golfkl%C3%BAbburinn-J%C3%B6kull-%C3%93lafsv%C3%ADk-1178725165481292/','golf course',55);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Patreksfjarðar','facebook.com/golfklubburpatreksfjardar','golf course',56);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Fjarðabyggðar','https://www.facebook.com/profile.php?id=100064910881478','golf course',58);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Reykholtsdalsvöllur','https://maps.app.goo.gl/wBf6mDQdDDLSFN4M8','golf course',59);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Reykjavíkur','www.grgolf.is','golf course',60);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Skagafjarðar','www.gss.is','golf course',62);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Selfoss','www.gosgolf.is','golf course',63);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Seyðisfjarðar','facebook.com/people/Golfkl%C3%BAbbur-Sey%C3%B0isfjar%C3%B0ar/100006083414146?_rdr','golf course',64);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Siglufjarðar','www.gksgolf.is','golf course',65);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn Flúðir','https://www.kaffisel.is/','golf course',67);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Garðavöllur undir Jökli','https://maps.app.goo.gl/cJ94XSRaBL4cBkar7','golf course',70);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn Mostri','mostri.is','golf course',73);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Vestmannaeyja','gvgolf.is','golf course',76);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn í Vík','facebook.com/golfklubburinnvik/','golf course',77);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Vopnafjarðar','facebook.com/Golfkl%C3%BAbbur-Vopnafjar%C3%B0ar-1601339420137698','golf course',78);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbburinn Dalbúi','dalbui.is','golf course',79);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Golfklúbbur Þorlákshafnar','facebook.com/golfklubburthorlakshafnar','golf course',81);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaug Akureyrar','https://sundlaugar.is/en/sundlaugasafn/akureyri-swimming-pool/','swimming pool',3);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Lundi','https://sundlaugar.is/en/sundlaugasafn/lundur-i-oxarfirdi-2/','swimming pool',4);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Varmalandi','https://sundlaugar.is/en/sundlaugasafn/ithrottamidstodin-varmalandi-2/','swimming pool',6);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Bíldudal','https://maps.app.goo.gl/5KXUvTMxi5yjPFxv8','swimming pool',7);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Blönduós','https://sundlaugar.is/en/sundlaugasafn/blonduos-swimming-pool/','swimming pool',9);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Bolungarvík','https://sundlaugar.is/en/sundlaugasafn/sundlaug-bolungarvikur/','swimming pool',10);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Borganesi','https://sundlaugar.is/en/sundlaugasafn/ithrottamidstodin-borgarnesi-2-2/','swimming pool',12);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Dalvík','https://sundlaugar.is/en/sundlaugasafn/dalvik-2/','swimming pool',14);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Krossneslaug','https://maps.app.goo.gl/b5aTMNSq8MkhyxTs7','swimming pool',15);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Djúpavogi','https://sundlaugar.is/en/sundlaugasafn/sundlaug-djupavogs/','swimming pool',17);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin Egilsstöðum','https://sundlaugar.is/en/sundlaugasafn/sundlaugin-egilsstodum-2/','swimming pool',18);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Eskifirði','https://sundlaugar.is/en/sundlaugasafn/eskifjordur/','swimming pool',19);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Þorlákshöfn','https://sundlaugar.is/en/sundlaugasafn/thorlakshofn-2/','swimming pool',20);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Flateyri','https://sundlaugar.is/en/sundlaugasafn/faskrudsfjordur-2/','swimming pool',21);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Flateyri','https://sundlaugar.is/en/sundlaugasafn/flateyri-2/','swimming pool',22);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Flúðum','https://sundlaugar.is/en/sundlaugasafn/fludir-2/','swimming pool',23);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Ásgarðslaug','https://sundlaugar.is/en/sundlaugasafn/asgardslaug/','swimming pool',24);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Garði','https://sundlaugar.is/en/sundlaugasafn/sundlaugin-gardi/','swimming pool',25);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Grímsey','https://sundlaugar.is/en/sundlaugasafn/sundlaug-grimseyjar-2/','swimming pool',26);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Skútustaðahreppi','https://maps.app.goo.gl/aVNwzRXqcjDo2F8T6','swimming pool',27);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Grindavík','https://sundlaugar.is/en/sundlaugasafn/sundlaug-grindavikur/','swimming pool',28);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaug Bláskógarbyggðar','https://maps.app.goo.gl/uQKrAZ5XhTiagn3j9','swimming pool',30);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugar í Hafnafirði','https://hafnarfjordur.is/thjonusta/ithrottir-og-utivera/sundlaugar/','swimming pool',31);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Hellu','https://sundlaugar.is/en/sundlaugasafn/hella-2/','swimming pool',34);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Höfn í Hornafirði','https://sundlaugar.is/en/sundlaugasafn/sundlaug-hafnar/','swimming pool',36);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Hólmavík','https://sundlaugar.is/en/sundlaugasafn/holmavik/','swimming pool',37);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Lindin Geothermal','https://www.husafell.com/activities/thermal-baths','swimming pool',38);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin Hlöðum','https://maps.app.goo.gl/gxLvppLCRyKrTd3N6','swimming pool',39);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Laugaskarð í Hveragerði','https://sundlaugar.is/en/sundlaugasafn/sundlaugin-laugaskardi-2/','swimming pool',40);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Hvolfsvelli','https://sundlaugar.is/en/sundlaugasafn/hvolsvollur/','swimming pool',41);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Ísafirði','https://sundlaugar.is/en/sundlaugasafn/sundholl-isafjardar-2/','swimming pool',42);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Reykjanesbæ','https://sundlaugar.is/en/sundlaugasafn/reykjanesbaer-vatnaverold-2/','swimming pool',43);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Kirkjubæjarklaustri','https://sundlaugar.is/en/sundlaugasafn/kirkjubaejarklaustur-2/','swimming pool',44);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Klébergslaug','https://sundlaugar.is/en/sundlaugasafn/klebergslaug-2/','swimming pool',45);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugar í Kópavogi','https://www.kopavogur.is/is/ibuar/ithrottir-utivist/sundlaugar-i-kopavogi','swimming pool',47);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Laugarvatni','https://sundlaugar.is/en/sundlaugasafn/laugarvatn-2/','swimming pool',49);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Lágafellslaug','https://sundlaugar.is/en/sundlaugasafn/lagafellslaug/','swimming pool',51);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Skútustaðahreppi','https://maps.app.goo.gl/aVNwzRXqcjDo2F8T6','swimming pool',52);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Neskaupstað','https://sundlaugar.is/en/sundlaugasafn/neskaupstadur-2/','swimming pool',53);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Ólafsfirði','https://sundlaugar.is/en/sundlaugasafn/olafsfjordur-swimming-pool/','swimming pool',54);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Patreksfirði','https://sundlaugar.is/en/sundlaugasafn/patreksfjordur-2/','swimming pool',56);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Raufarhöfn','https://sundlaugar.is/en/sundlaugasafn/raufarhofn-2/','swimming pool',57);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Reyðarfirði','https://sundlaugar.is/en/sundlaugasafn/reydarfjordur/','swimming pool',58);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Lindin Geothermal','https://www.husafell.com/activities/thermal-baths','swimming pool',59);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugar í Reykjavik','https://reykjavik.is/sundlaugar','swimming pool',60);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sælingsdalslaug','https://sundlaugar.is/sundlaugasafn/saelingsdalslaug/','swimming pool',61);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Sauðárkróki','https://sundlaugar.is/en/sundlaugasafn/saudarkrokur-2/','swimming pool',62);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Selfossi','https://sundlaugar.is/en/sundlaugasafn/sundholl-selfoss-2/','swimming pool',63);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Siglufirði','https://sundlaugar.is/en/sundlaugasafn/siglufjordur/','swimming pool',65);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Íþróttamiðstöðin í Reykholti','https://www.facebook.com/SportsCenterReykholti?paipv=0&eav=AfbGEIdkHSCaamymF8-vLdQqBhvxSFoolM2zTiGfXjeCU2EioYNw9e0GoEMJNMuOEyU','swimming pool',67);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Seljavallalaug','https://maps.app.goo.gl/wRF1vvCrXCANWAVZ6','swimming pool',68);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Lýsulaugar','https://lysulaugar.is/','swimming pool',70);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin Stykkishólmi','https://sundlaugar.is/en/sundlaugasafn/stykkisholmur-2/','swimming pool',73);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin Varmahlíð','https://sundlaugar.is/en/sundlaugasafn/varmahlid-2/','swimming pool',75);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Vestmannaeyjum','https://sundlaugar.is/en/sundlaugasafn/vestmannaeyjar-2/','swimming pool',76);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Vík','https://sundlaugar.is/en/sundlaugasafn/vik/','swimming pool',77);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Vopnafirði','https://vopnafjardarhreppur.is/thjonusta/ithrottir-og-tomstundir/sundlaug','swimming pool',78);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Borg','https://sundlaugar.is/en/sundlaugasafn/borg-grimsnesi-2/','swimming pool',79);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin á Neslaug','https://sundlaugar.is/sundlaugasafn/neslaug/?lang=en','swimming pool',80);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Sundlaugin í Þorlákshöfn','https://sundlaugar.is/en/sundlaugasafn/thorlakshofn-2/','swimming pool',81);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Dalbæ','https://tjalda.is/dalbaer/','camping',2);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hamrar','https://tjalda.is/hamrar/','camping',3);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Ásbyrgi','https://maps.app.goo.gl/RZQGtosTEzX4G9YEA','camping',4);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Borgarfirði','https://tjalda.is/borgarfjordur_eystri/','camping',5);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Varmaland','https://tjalda.is/varmaland/','camping',6);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Bíldudal','https://tjalda.is/bildudalur/','camping',7);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Breiðdalsvík','https://tjalda.is/breidavik/','camping',8);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Blönduós','https://tjalda.is/blonduos/','camping',9);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Bolungarvík','https://tjalda.is/bolungarvik/','camping',10);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Boreyri','https://tjalda.is/boreyri/','camping',11);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Borgarnes','https://tjalda.is/borgarnes/','camping',12);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Búðardal','https://tjalda.is/budardalur/','camping',13);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Dalvík','https://tjalda.is/dalvik/','camping',14);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Urðartind','https://tjalda.is/urartindur-norurfiri/','camping',15);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Djúpdal','https://tjalda.is/tjaldsvaedid_djupadal/','camping',16);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Djúpivogur','https://tjalda.is/djupivogur/','camping',17);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Egilsstaðir','https://tjalda.is/egilsstadir/','camping',18);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Eskifirði','https://tjalda.is/eskifjorur/','camping',19);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Eyrarbakka','https://tjalda.is/eyrarbakki/','camping',20);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Fáskrúðsfirði','https://tjalda.is/faskrudsfjordur/','camping',21);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Korpudal','https://tjalda.is/korpudalur/','camping',22);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Flúðir','https://tjalda.is/fludir/','camping',23);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hafnarfirði','https://tjalda.is/hafnarfjordur/','camping',24);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Garðaskaga','https://tjalda.is/gardskagi/','camping',25);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hlíð','https://tjalda.is/hlid/','camping',27);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Grindavík','https://tjalda.is/grindavik/','camping',28);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Skjól','https://tjalda.is/skjol/','camping',30);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hafnarfirði','https://tjalda.is/hafnarfjordur/','camping',31);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hallkelsstaðahlíð við Hlíðarvatn','https://tjalda.is/hallkelsstadahlid/','camping',32);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hallormsstaðaskóg','https://tjalda.is/hallormsstadaskogur/','camping',33);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hellu','https://tjalda.is/hella-gaddstadaflatir/','camping',34);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hellisandi','https://tjalda.is/hellissandur/','camping',35);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Höfn í Hornafirði','https://tjalda.is/tjaldsvaedid-hofn-i-hornafirdi/','camping',36);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hólmavík','https://tjalda.is/holmavik/','camping',37);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Húsafell','https://tjalda.is/husafell/','camping',38);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hlaðir','https://tjalda.is/hladir/','camping',39);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hveragerði','https://tjalda.is/hveragerdi/','camping',40);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hvolsvelli','https://tjalda.is/hvolsvollur/','camping',41);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Torfnes','https://tjalda.is/torfnes/','camping',42);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Keflavík','https://tjalda.is/happycampsite/','camping',43);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Kópaskeri','https://tjalda.is/kopasker/','camping',46);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hafnarfirði','https://tjalda.is/hafnarfjordur/','camping',47);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Laugar','https://tjalda.is/laugar-camping/','camping',48);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Laugavatni','https://tjalda.is/laugarvatn/','camping',49);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Möðrudal','https://tjalda.is/fjalladyrd-modrudal/','camping',50);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Mosskógar','https://tjalda.is/mosskogar/','camping',51);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hlíð í Mývatni','https://tjalda.is/hlid/','camping',52);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Neskaupsstað','https://tjalda.is/neskaupstadur/','camping',53);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Ólafsfirði','https://tjalda.is/olafsfjordur/','camping',54);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Ólafsvík','https://tjalda.is/olafsvik/','camping',55);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Patreksfirði','https://tjalda.is/patreksfjordur/','camping',56);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Raufarhöfn','https://tjalda.is/raufarhofn/','camping',57);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Reyðarfirði','https://tjalda.is/reydarfjordur/','camping',58);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Hverinn','https://tjalda.is/hverinn/','camping',59);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Laugardal','https://tjalda.is/laugardalur/','camping',60);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Laugar','https://tjalda.is/laugar/','camping',61);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Sauðárkróki','https://tjalda.is/saudarkrokur/','camping',62);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Selfoss','https://tjalda.is/gesthus/','camping',63);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Seyðisfirði','https://tjalda.is/seyisfjordur/','camping',64);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Siglufirði','https://tjalda.is/siglufjordur/','camping',65);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Skaftafelli','https://tjalda.is/skaftafell/','camping',66);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Reykholti','https://tjalda.is/reykholt/','camping',67);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Skógarfoss','https://tjalda.is/skogafoss/','camping',68);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Snorrastaðir','https://tjalda.is/snorrastadir/','camping',69);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Stafafelli','https://tjalda.is/stafafell/','camping',71);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Stuðlagil','https://tjalda.is/studlagil/','camping',72);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Stykkishólmi','https://tjalda.is/stykkisholmur/','camping',73);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Súðavík','https://tjalda.is/sudavik/','camping',74);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Varmahlíð','https://tjalda.is/varmahlid/','camping',75);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Vestmannaeyja','https://tjalda.is/vestmannaeyjar/','camping',76);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Þakgil','https://tjalda.is/thakgil/','camping',77);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Ásbrandsstaðir','https://tjalda.is/asbrandsstadir/','camping',78);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Úlfljótsvatn','https://tjalda.is/ulfljotsvatn/','camping',79);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Þjórsárdal','https://tjalda.is/thjorsardalur/','camping',80);
INSERT INTO leisures(name,link,type,place_id) VALUES ('Tjaldsvæðið Þorlákshöfn','https://tjalda.is/thorlakshofn/','camping',81);
